remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: Space Shooter
description: Introducting the nostalgic 2D Space Shooter game where you blast through the cosmos, take down enemy ships, and avoid asteroids in this thrilling arcade adventure. Explore the documented development process behind the game, showcasing C++ game development project, custom libraries, and a passion for creating immersive gaming experiences. Upgrade your ship, grab power-ups, and set your sights on conquering the vastness of space!
